<x-superadmin-layout>
    <div class="space-y-6">
        @if(session('success'))<div class="rounded-lg bg-green-50 p-4 text-sm font-semibold text-green-800">{{ session('success') }}</div>@endif
        @if($errors->any())<div class="rounded-lg bg-red-50 p-4 text-sm font-semibold text-red-700">{{ $errors->first() }}</div>@endif

        <section class="rounded-2xl border bg-white p-5 sm:p-7">
            <div class="flex flex-col gap-6 lg:flex-row lg:items-start lg:justify-between">
                <div class="flex min-w-0 items-center gap-4"><img src="{{ $photographer->profilePhotoUrl() }}" alt="Foto {{ $photographer->name }}" class="h-20 w-20 rounded-full object-cover sm:h-24 sm:w-24"><div class="min-w-0"><div class="flex flex-wrap gap-2"><span class="rounded-full px-3 py-1 text-xs font-bold {{ $photographer->is_active ? 'bg-green-100 text-green-800' : 'bg-gray-200 text-gray-700' }}">{{ $photographer->is_active ? 'AKTIF' : 'NONAKTIF' }}</span><span class="rounded-full bg-gray-100 px-3 py-1 text-xs font-bold uppercase">{{ $photographer->verificationState() }}</span></div><h1 class="mt-3 truncate">{{ $photographer->studio_name ?: $photographer->name }}</h1><p class="helper mt-1">{{ $photographer->email }} &middot; {{ $photographer->location ?: 'Lokasi belum diisi' }}</p></div></div>
                <div class="flex flex-wrap gap-2"><a href="{{ route('superadmin.photographers.edit', $photographer) }}" class="button rounded-lg border px-4 py-3">Edit Detail</a><form method="POST" action="{{ route('superadmin.photographers.status', $photographer) }}">@csrf @method('PATCH')<input type="hidden" name="is_active" value="{{ $photographer->is_active ? 0 : 1 }}"><button class="rounded-lg px-4 py-3 {{ $photographer->is_active ? 'border border-red-200 text-red-700' : 'bg-black text-white' }}" onclick="return confirm('{{ $photographer->is_active ? 'Nonaktifkan' : 'Aktifkan' }} akun ini?')">{{ $photographer->is_active ? 'Nonaktifkan' : 'Aktifkan' }}</button></form></div>
            </div>
            <div class="mt-7 grid grid-cols-2 gap-3 border-t pt-6 sm:grid-cols-4">@foreach([['Foto',$photographer->photos_count],['Event',$photographer->events_count],['Kamera',$photographer->cameras_count],['Penjualan',$photographer->paid_sales_count]] as [$label,$value])<div><p class="metric">{{ number_format($value) }}</p><p class="text-xs font-bold uppercase text-gray-500">{{ $label }}</p></div>@endforeach</div>
        </section>

        <div class="grid gap-6 xl:grid-cols-[1fr_1.3fr]">
            <section class="rounded-2xl border bg-white p-6"><h2>Detail Profil</h2><dl class="mt-5 grid gap-4 text-sm sm:grid-cols-2">@foreach([['Nama',$photographer->name],['Slug',$photographer->slug],['Kategori',$photographer->category],['WhatsApp',$photographer->whatsapp],['Instagram',$photographer->instagram_username ? '@'.$photographer->instagram_username : null],['Paket',$photographer->package?->display_name ?? $photographer->package?->nama_paket],['Saldo','Rp'.number_format($photographer->saldo,0,',','.')],['Pendapatan paid','Rp'.number_format($photographer->paid_revenue ?? 0,0,',','.')]] as [$label,$value])<div><dt class="text-gray-500">{{ $label }}</dt><dd class="mt-1 font-bold">{{ $value ?: '—' }}</dd></div>@endforeach</dl><div class="mt-5 border-t pt-5"><p class="text-sm text-gray-500">Bio</p><p class="mt-2 text-sm leading-6">{{ $photographer->bio ?: 'Belum diisi.' }}</p></div></section>
            <section class="rounded-2xl border bg-white p-6"><h2>Kamera</h2><div class="mt-5 grid gap-4 sm:grid-cols-2">@forelse($photographer->cameras as $camera)<article class="overflow-hidden rounded-xl border">@if($camera->photo_path)<img src="{{ route('media.camera', $camera) }}" alt="{{ $camera->brand_model }}" class="aspect-video w-full object-cover">@endif<div class="p-4"><h3>{{ $camera->brand_model }}</h3><p class="helper mt-1">{{ $camera->name }}{{ $camera->lens ? ' · '.$camera->lens : '' }}</p></div></article>@empty<p class="helper sm:col-span-2">Belum ada kamera.</p>@endforelse</div></section>
        </div>

        <section class="rounded-2xl border bg-white p-6"><div class="flex items-center justify-between"><h2>Foto terbaru</h2>@if($photographer->is_verified && $photographer->is_active)<a href="{{ route('photographers.show', $photographer->slug ?: $photographer->id) }}" target="_blank" class="text-sm font-bold underline">Lihat profil publik</a>@endif</div><div class="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-4">@forelse($photographer->photos as $photo)<article><img src="{{ route('media.preview', $photo) }}" alt="{{ $photo->title }}" class="aspect-[4/3] w-full rounded-lg object-cover"><p class="mt-2 truncate text-sm font-bold">{{ $photo->title }}</p></article>@empty<p class="helper col-span-full">Belum ada foto.</p>@endforelse</div></section>

        <section class="rounded-2xl border border-red-200 bg-red-50 p-6"><h2 class="text-red-800">Hapus akun</h2><p class="helper mt-2 text-red-700">Akun hanya dapat dihapus jika belum memiliki foto, event, kamera, transaksi, atau penarikan. Untuk akun yang sudah beroperasi, gunakan status nonaktif.</p><form method="POST" action="{{ route('superadmin.photographers.destroy', $photographer) }}" class="mt-4">@csrf @method('DELETE')<button class="rounded-lg border border-red-300 bg-white px-4 py-3 text-red-700" onclick="return confirm('Hapus permanen akun photographer ini?')">Hapus Photographer</button></form></section>
    </div>
</x-superadmin-layout>

