<x-superadmin-layout>
    <div class="space-y-8">
        <div><h1>Subscriptions & Payments</h1><p class="helper mt-2">Entitlement aktif, histori order, konflik pembayaran, dan review refund.</p></div>
        @if(session('success'))<div class="rounded-lg bg-green-50 p-4 text-sm text-green-800">{{ session('success') }}</div>@endif
        <section class="overflow-hidden rounded-2xl border bg-white"><div class="overflow-x-auto"><table class="w-full"><thead class="bg-gray-50"><tr>@foreach(['Photographer','Paket','Status','Mulai','Berakhir','Versi'] as $head)<th class="p-4 text-left">{{ $head }}</th>@endforeach</tr></thead><tbody class="divide-y">@forelse($subscriptions as $subscription)<tr><td class="p-4"><strong>{{ $subscription->user?->name }}</strong><small class="block text-gray-500">{{ $subscription->user?->email }}</small></td><td class="p-4">{{ $subscription->entitlement_snapshot['name'] ?? $subscription->package?->display_name }}</td><td class="p-4 uppercase">{{ $subscription->isActive() ? 'active' : $subscription->status }}</td><td class="p-4">{{ $subscription->starts_at?->format('d M Y H:i') }}</td><td class="p-4">{{ $subscription->ends_at?->format('d M Y H:i') }}</td><td class="p-4">v{{ $subscription->version }}</td></tr>@empty<tr><td colspan="6" class="p-8 text-center">Belum ada subscription.</td></tr>@endforelse</tbody></table></div><div class="p-4">{{ $subscriptions->links() }}</div></section>
        <section class="overflow-hidden rounded-2xl border bg-white"><div class="border-b p-5"><h2>Order terbaru</h2></div><div class="overflow-x-auto"><table class="w-full"><thead class="bg-gray-50"><tr>@foreach(['Order','User','Intent','Nominal','Status','Paid at','Review'] as $head)<th class="p-4 text-left">{{ $head }}</th>@endforeach</tr></thead><tbody class="divide-y">@forelse($orders as $order)<tr><td class="p-4">{{ $order->order_id }}</td><td class="p-4">{{ $order->user?->email }}</td><td class="p-4">{{ $order->intent }}</td><td class="p-4">Rp{{ number_format($order->gross_amount) }}</td><td class="p-4">{{ $order->status }}</td><td class="p-4">{{ $order->provider_paid_at?->format('d M Y H:i') ?? '—' }}</td><td class="p-4">{{ $order->requires_review ? 'Perlu review' : '—' }}</td></tr>@empty<tr><td colspan="7" class="p-8 text-center">Belum ada order.</td></tr>@endforelse</tbody></table></div></section>
        <section class="overflow-hidden rounded-2xl border bg-white"><div class="border-b p-5"><h2>Refund review</h2></div><div class="divide-y">@forelse($refunds as $refund)<form class="grid gap-3 p-5 md:grid-cols-[1fr_auto_auto]" method="POST" action="{{ route('superadmin.subscription-refunds.review', $refund) }}">@csrf @method('PATCH')<div><strong>Rp{{ number_format($refund->amount) }}</strong><p class="text-sm text-gray-500">{{ $refund->reason }}</p></div><select class="rounded-lg border-gray-300" name="status"><option value="approved">Approve</option><option value="rejected">Reject</option></select><button class="rounded-lg bg-black px-4 py-2 text-white">Simpan</button></form>@empty<p class="p-8 text-center">Belum ada refund.</p>@endforelse</div></section>
    </div>
</x-superadmin-layout>
