<x-fg-layout>
<div class="space-y-7" x-data="{ latest: {{ $sales->first()?->id ?? 0 }}, newSale: false }" x-init="setInterval(async () => { const r = await fetch('{{ route('fotografer.dashboard.data') }}'); if (r.ok) { const d = await r.json(); if (d.latest_id > latest) { latest = d.latest_id; newSale = true; } } }, 15000)">
    <div x-cloak x-show="newSale" class="rounded-lg border border-gray-900 bg-gray-900 p-4 text-sm font-semibold text-white">Penjualan baru diterima. <button type="button" class="ml-2 underline" @click="window.location.reload()">Perbarui data</button></div>
    <div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="helper uppercase font-bold tracking-widest">Ringkasan</p><h1>Selamat datang, {{ $user->name }}</h1><p class="helper mt-2">Data penjualan, saldo, dan aktivitas karya Anda.</p></div><a class="button rounded-lg bg-black px-5 py-3 text-white" href="{{ route('fotografer.photos.index') }}">Upload foto</a></div>
    @if(session('success'))<div class="rounded-lg bg-green-50 p-4 text-sm font-semibold text-green-800">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="rounded-lg bg-red-50 p-4 text-sm text-red-800">{{ $errors->first() }}</div>@endif
    <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        @foreach([['PENDAPATAN BERSIH','Rp'.number_format($stats['earnings'],0,',','.'),'Akumulasi transaksi paid (90%)'],['FOTO TERJUAL',number_format($stats['sold']),'Pembelian paid'],['TOTAL KUNJUNGAN',number_format($stats['visits']),'Tampilan detail foto'],['RASIO KONVERSI BELI',$stats['conversion'].'%','Pembelian dibagi kunjungan']] as $card)
        <section class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><p class="text-xs font-bold tracking-wider text-gray-500">{{ $card[0] }}</p><p class="metric mt-4">{{ $card[1] }}</p><p class="helper mt-2">{{ $card[2] }}</p></section>
        @endforeach
    </div>
    <div class="grid gap-6 xl:grid-cols-3">
        <section class="rounded-2xl border border-gray-200 bg-white p-6 xl:col-span-2"><h2>Tren penjualan 30 hari</h2><div class="mt-6 flex h-52 items-end gap-1 overflow-x-auto">@php($max=max(1,collect($chart)->max('photographer')))@forelse($chart as $day)<div class="flex min-w-8 flex-1 flex-col items-center justify-end gap-2" title="{{ $day['day'] }} — Rp{{ number_format($day['photographer']) }}"><div class="w-full rounded-t bg-black" style="height: {{ max(3, $day['photographer']/$max*170) }}px"></div><span class="text-[11px] text-gray-500">{{ \Carbon\Carbon::parse($day['day'])->format('d') }}</span></div>@empty<p class="helper self-center">Belum ada transaksi paid dalam 30 hari.</p>@endforelse</div></section>
        <section class="rounded-2xl border border-gray-200 bg-white p-6"><p class="text-sm font-bold text-gray-500">SALDO SIAP TARIK</p><p class="metric mt-3">Rp{{ number_format($stats['balance'],0,',','.') }}</p><p class="helper mt-2">Minimum Rp{{ number_format(\App\Models\PlatformSetting::minimumWithdrawal(),0,',','.') }}</p><form class="mt-5 space-y-3" method="POST" action="{{ route('fotografer.withdrawals.store') }}">@csrf<input type="hidden" name="idempotency_key" value="{{ (string) Str::uuid() }}"><input class="w-full rounded-lg border-gray-300 text-sm" type="number" name="jumlah_tarik" placeholder="Nominal" required><select class="w-full rounded-lg border-gray-300 text-sm" name="destination_type" x-data @change="$refs.method.placeholder=$event.target.value==='bank'?'Nama bank':'Provider e-wallet'"><option value="bank">Bank</option><option value="ewallet">E-Wallet</option></select><input x-ref="method" class="w-full rounded-lg border-gray-300 text-sm" name="metode_pembayaran" placeholder="Nama bank" required><input class="w-full rounded-lg border-gray-300 text-sm" name="nomor_tujuan" placeholder="Nomor rekening / telepon" required><input class="w-full rounded-lg border-gray-300 text-sm" name="account_holder" placeholder="Nama pemilik"><button class="w-full rounded-lg bg-black px-4 py-3 text-white">Ajukan penarikan</button></form></section>
    </div>
    <section class="overflow-hidden rounded-2xl border border-gray-200 bg-white"><div class="flex items-center justify-between p-5"><h2>Penjualan terkini</h2><a class="text-sm font-bold underline" href="{{ route('fotografer.orders') }}">Lihat semua</a></div><div class="overflow-x-auto"><table class="w-full"><thead class="bg-gray-50"><tr><th class="p-4 text-left">Order</th><th class="p-4 text-left">Foto / Event</th><th class="p-4 text-left">Pembeli</th><th class="p-4 text-right">Harga</th><th class="p-4 text-right">Bagian Anda</th><th class="p-4 text-right">Waktu</th></tr></thead><tbody class="divide-y">@forelse($sales as $sale)<tr><td class="p-4 font-bold">{{ $sale->order_number ?? '#'.$sale->id }}</td><td class="p-4">{{ $sale->photo?->title }}<span class="block text-xs text-gray-500">{{ $sale->photo?->event?->nama_event }}</span></td><td class="p-4">{{ $sale->pembeli?->name ?? $sale->pembeli?->email }}</td><td class="p-4 text-right">Rp{{ number_format($sale->harga_foto) }}</td><td class="p-4 text-right font-bold">Rp{{ number_format($sale->jumlah_fotografer) }}</td><td class="p-4 text-right">{{ ($sale->paid_at ?? $sale->created_at)->diffForHumans() }}</td></tr>@empty<tr><td class="p-8 text-center text-gray-500" colspan="6">Belum ada penjualan.</td></tr>@endforelse</tbody></table></div><div class="p-4">{{ $sales->links() }}</div></section>
    <section class="rounded-2xl border border-gray-200 bg-white p-6"><h2>Penarikan terbaru</h2><div class="mt-4 grid gap-3">@forelse($withdrawals as $withdrawal)<div class="flex flex-wrap items-center justify-between rounded-lg bg-gray-50 p-4"><div><strong>Rp{{ number_format($withdrawal->jumlah_tarik) }}</strong><p class="helper">{{ $withdrawal->metode_pembayaran }} · {{ $withdrawal->created_at->format('d M Y') }}</p>@if($withdrawal->status==='rejected')<p class="mt-1 text-sm text-red-700">{{ $withdrawal->admin_notes }}</p>@endif</div><span class="rounded-full border px-3 py-1 text-xs font-bold uppercase">{{ $withdrawal->status }}</span></div>@empty<p class="helper">Belum ada penarikan.</p>@endforelse</div></section>
</div>
</x-fg-layout>
